config/routes.rb
NewsApp::Application.routes.draw do
  resources :comments

  resources :users

  resources :news
  match 'clear_cookies' => 'news#clear_cookies'
  match 'notification_refresh' => 'news#notification_refresh'
  match 'show/:id' => 'news#show', :as=> :show
  match 'comments/new/:id' => 'comments#new'

   root :to => 'news#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :news
end

app/models/news.rb
class News < ActiveRecord::Base
  has_and_belongs_to_many :users
  scope :limit,lambda {|limit|{:limit =>limit}}
  has_many :comments, :dependent => :destroy

  after_save do |news|
    `curl http://localhost:9292/faye -d 'message={"channel":"/news/new", "data":"#{self.data}"}'`
  end
end

app/models/news_user.rb
class NewsUser < ActiveRecord::Base

end

app/models/read_message.rb
class ReadMessage < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :news
  has_many :comments, :dependent => :destroy


  def unread_news(user_id)
    count = (News.all.collect(&:id) - ReadMessage.where("user_id = #{user_id}").collect(&:news_id))
    return count
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new
    @user = User.find(params[:user_id])
    @news=News.find(params[:message_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create

    @comment = Comment.new(params[:comment])
    @user = User.find(params[:user_id])
    @news = News.find(params[:message_id])
    @comment.news_id = @news.id
    @comment.user_id = @user.id
    @comment.name = @user.name
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :ok }
    end
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  # GET /news
  # GET /news.json
  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])
    ReadMessage.create(:user_id => session[:user_name].id, :news_id => params[:id]) if session[:user_name] and params[:id]
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/new
  # GET /news/new.json
  def new
    @news = News.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
  end

  # POST /news
  # POST /news.json
  def create

    params[:news][:name].blank? ? (@news = News.new(params[:news])) : (@news = News.new(params[:news]))
    if session[:user_name].blank?
    @user = User.new
    @user.name = params[:news][:name]
    if @user.save and session[:user_name].blank?
    session[:user_name] = @user
    end
    end
    respond_to do |format|
      if @news.save

        NewsUser.create(:news_id =>@news.id,:user_id => session[:user_name].id)
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render json: @news, status: :created, location: @news }
      else
        format.html { render action: "new" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end
def clear_cookies
  session[:user_name] = nil
  session[:user_name] = ""
  @news=News.all
  render :action => 'index'
  return
end
  # PUT /news/1
  # PUT /news/1.json
  def update
    @news = News.find(params[:id])

    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :ok }
    end
  end

  def notification_refresh
    @user = session[:user_name]
    @messages = @user.unread_news(@user.id)
    render :partial => "/news/notification_refresh"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
    <%= hidden_field_tag 'user_id', params[:user_id]%>
    <%= hidden_field_tag 'message_id', params[:message_id]%>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= @user.name %>
  </div>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Comment Made By</th>
    <th>Comment posted</th>
    <th>News</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.user.name if comment.user%></td>
    <td><%= comment.comment %></td>
    <td><%= comment.news.data if comment.news%></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%#= link_to 'Destroy', comment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%#= link_to 'New Comment', new_comment_path %>
<%= link_to 'Start News', '/news/new' %>
<%= link_to 'Home', '/news' %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @comment.name %>
</p>

<p>
  <b>User:</b>
  <%= User.find(@comment.user_id).name %>
</p>

<p>
  <b>Comment:</b>
  <%= @comment.comment %>
</p>

<p>
  <b>News:</b>
  <%= @comment.news_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %> |
<%= link_to 'Home', '/news/new' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewsApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag :defaults, "http://localhost:9292/faye.js" %>
</head>
<body>
<div class="container">

  <div class="header">
    <div class="menu">
      <h2>News Bulletin App</h2>
   <!--   <div class="circleBase type1"></div> -->
      <%if session[:user_name]%>
          <p>Welcome!! You are logged in.</p>
      <%end%>
    </div>
    <!--<ul id="nav">-->
      <!--<li><a href="#">Link1</a></li>-->
      <!--<li><a href="#">Link2</a></li>-->
      <!--<li id="notification_li">-->
        <!-- <a href="#" id="notificationLink">Notifications</a>-->
      <!--<li id="notification_li">-->


        <!--<div id="notificationContainer">-->
          <!--<div id="notificationTitle">Notifications</div>-->
    <div class="counter"><span id="notification_count"><%=session[:user_name].unread_news(session[:user_name].id).count if session[:user_name]%></span>
      <a href="#" id="notificationLink">New Notifications</a></div>
          <ul id="notification_ajax">

            <%if session[:user_name]%>
                <%News.find(session[:user_name].unread_news(session[:user_name].id)).reverse[0..5].each do |a|%>
                    <li><a href="/show/<%=a.id%>"><%= a.data%></a></li>
                <%end%>
            <%end%>
            <li><a href="/news">See All</a></li>
          </ul>
        <!--</div>-->

      <!--</li>-->
      <!--</li>-->
    <!--</ul>-->
<%= yield %>
</div>
    </div>
</body>
</html>

app/views/news/_form.html.erb
<script type="text/javascript" >

</script>




    <div class="main_body">
      <%= form_for(@news) do |f| %>
          <% if @news.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

                <ul>
                  <% @news.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>
<%if session[:user_name].blank?%>
          <div class="new_field">
            <%= f.label :name %><br />
            <%= f.text_field :name %>
          </div>
              <%end%>
          <div class="new_field">
           <!-- <%= f.label :data %>--><br />
            <%= f.text_area :data %>
          </div>
          <div class="new_actions">
            <%= f.submit %>
          </div>
      <% end %>

      <div class="footer">


      </div>
    </div>

<%=link_to 'Show Comments', '/comments'%> |
<%=link_to 'Show All News', '/news'%>


<style>


</style>

app/views/news/_notification_refresh.html.erb
<%if session[:user_name]%>
    <%News.find(session[:user_name].unread_news(session[:user_name].id)).reverse[0..5].each do |a|%>
        <li><a href="/show/<%=a.id%>"><%= a.data%></a></li>
    <%end%>
<%end%>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<div class="test-scroll">
<table>
  <tr>
    <th>News Posted By</th>
    <th>News</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @news.each do |news| %>
  <tr>
    <td><%= news.name %></td>
    <td><%= news.data %></td>
    <td><%= link_to 'Show', news %></td>
    <td><%= link_to 'Edit', edit_news_path(news) %></td>
    <td><%= link_to("Comment on this News", { :controller => "/comments", :action=>'new', :user_id => session[:user_name].id,:message_id=>news.id}) %>
    </td>
  </tr>
<% end %>
</table>
</div>
<br />

<%= link_to 'New News', new_news_path %>

app/views/news/new.html.erb
<%= render 'form' %>

<%#= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>News Posted By:</b>
  <%= @news.name %>
</p>

<p>
  <b>News:</b>
  <%= @news.data %>
</p>


<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Home', '/news/new' %> |
<%= link_to("Comment on this News", { :controller => "/comments", :action=>'new', :user_id => session[:user_name].id,:message_id=>params[:id]}) %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>